### ISSUE TITLE
Uninitialized constant #<Module:0x00005604c6ddb140>::NR_TRANSACTION_CATEGORY

### ISSUE THREAD

**Issue by dv-hoang** [instructure/switchman-inst-jobs#2]
Got uninitialized constant error when enabling NewRelic
```
NameError (uninitialized constant #<Module:0x00005604c6ddb140>::NR_TRANSACTION_CATEGORY):
  /var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-inst-jobs-3.1.0/lib/switchman_inst_jobs/new_relic.rb:9:in `invoke_job'
  /var/canvas/vendor/bundle/ruby/2.6.0/gems/inst-jobs-2.1.3/lib/delayed/worker.rb:228:in `block (2 levels) in perform'

```

**Comment by ccutrer** [comment]
This is a stale issue. Please reopen if you're still having issues.
